In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [8]:
#!wget  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-11 15:51:44--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1,4M) [text/plain]
Saving to: 'data.csv'

     0K .......... .......... .......... .......... ..........  3% 3,04M 0s
    50K .......... .......... .......... .......... ..........  6% 82,0M 0s
   100K .......... .......... .......... .......... .......... 10% 26,9M 0s
   150K .......... .......... .......... .......... .......... 13% 11,2M 0s
   200K .......... .......... .......... .......... .......... 17% 9,71M 0s
   250K .......... .......... .......... .......... .......... 20% 7,07M 0s
   300K .......... .......... .......... .......... .......... 24% 43,2M 0s
   350K ..

# Question 1
#### What's the version of NumPy that you installed?

#### You can get the version information using the __version__ field:

In [2]:
np.__version__

'1.20.3'

# Question 2
#### How many records are in the dataset?

#### Here you need to specify the number of rows.

In [9]:
df = pd.read_csv('data.csv')
len(df)

11914

## Question 3
#### Who are the most frequent car manufacturers (top-3) according to the dataset?

In [10]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
df['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [12]:
df['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

## Question 4
##### What's the number of unique Audi car models in the dataset?

In [13]:
len(df[df.Make=='Audi']['Model'].unique())

34

## Question 5
#### How many columns in the dataset have missing values?

In [14]:
(df.isnull().sum()>0).values.sum()

5

## Question 6


In [25]:
# 1. Find the median value of "Engine Cylinders" column in the dataset.
print("Median value of Engine Cylinders: ",df['Engine Cylinders'].median())
# 2.Next, calculate the most frequent value of the same "Engine Cylinders".}
frecValue = df['Engine Cylinders'].value_counts().index[0]
print("Most frequent value of Engine Cylinders: ", frecValue)
# 3. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.
print("N Nulls in Engine Cylinders:", df.isnull().sum()['Engine Cylinders'])
print("Fill the missing values... ")
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(frecValue)
print("N Nulls in Engine Cylinders:", df.isnull().sum()['Engine Cylinders'])
# 4.Now, calculate the median value of "Engine Cylinders" once again.
print("Median value of Engine Cylinders: ",df['Engine Cylinders'].median())
print("No. The value doesn't change")

Median value of Engine Cylinders:  6.0
Most frequent value of Engine Cylinders:  4.0
N Nulls in Engine Cylinders: 0
Fill the missing values... 
N Nulls in Engine Cylinders: 0
Median value of Engine Cylinders:  6.0
The value does change but it is very close


## Question 7

In [16]:
print('1.Select all the "Lotus" cars from the dataset.')
df[df['Make']=='Lotus'].head(3)

1.Select all the "Lotus" cars from the dataset.


Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250

In [17]:
print('2. Select only columns "Engine HP", "Engine Cylinders".')
df[df['Make']=='Lotus'][["Engine HP","Engine Cylinders"]].head(3)

2. Select only columns "Engine HP", "Engine Cylinders".


Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0

In [18]:
print("3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).")
df[df['Make']=='Lotus'][["Engine HP","Engine Cylinders"]].drop_duplicates()

3. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).


Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [19]:
print("4. Get the underlying NumPy array. Let's call it X.")
X = df[df['Make']=='Lotus'][["Engine HP","Engine Cylinders"]].drop_duplicates().values
print(X.shape)
X

4. Get the underlying NumPy array. Let's call it X.
(9, 2)


array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [20]:
print("5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.")
XTX = X.T.dot(X)
print(XTX.shape)
XTX

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
(2, 2)


array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [21]:
print("6. Invert XTX.")
XTX_i = np.linalg.inv(XTX)
XTX_i


6. Invert XTX.


array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [22]:
print("7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].")
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
print('y = ', y)


7. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y =  [1100  800  750  850 1300 1000 1000 1300  800]


In [23]:
print("8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.")
w = XTX_i.dot(X.T).dot(y)
w

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.


array([  4.59494481, -63.56432501])

In [24]:
print ("9. What's the value of the first element of w?")
w[0]


9. What's the value of the first element of w?


4.594944810094551